### ISSUE TITLE
Раздел "Статистика"

### ISSUE THREAD

**Issue by Ana-Majer** [eqour/eireen#2]
Мальчики, добавила на сайт раздел "Статистика", посмотрите, если все устраивает, закрою задачу по этому разделу)

**Comment by eqour** [comment]
Для маленьких экранов изображение с графиком слишком большое: не помещается на всю ширину, либо выходит за рамки страницы

![IMG_20211210_013149.jpg](https://user-images.githubusercontent.com/94632924/145479050-6a76bd26-2478-459a-bd1a-3f06202538b7.jpg)
![IMG_20211210_013048.jpg](https://user-images.githubusercontent.com/94632924/145479079-cbe7ab93-265c-472b-9c6a-1cc885b634d6.jpg)

**Comment by Ana-Majer** [comment]
> Для маленьких экранов изображение с графиком слишком большое: не помещается на всю ширину, либо выходит за рамки страницы
> 
> ![IMG_20211210_013149.jpg](https://user-images.githubusercontent.com/94632924/145479050-6a76bd26-2478-459a-bd1a-3f06202538b7.jpg) ![IMG_20211210_013048.jpg](https://user-images.githubusercontent.com/94632924/145479079-cbe7ab93-265c-472b-9c6a-1cc885b634d6.jpg)

Исправила, оцени, если все устраивает, то раздел "Статистика" готов)

**Comment by eqour** [comment]
Отлично, всё устраивает 👍
