### ISSUE TITLE
Create a section on the landing page

### ISSUE THREAD

**Issue by eqour** [eqour/eireen#6]
Необходимо создать раздел на целевой странице, который в дальнейшем будет ссылаться на другую страницу с более подробным описанием.

**Comment by Ana-Majer** [comment]
Сделала, добавила в index, оцени, если все устраивает, то раздел "Как это работает" на главной странице готов)

**Comment by eqour** [comment]
На изображении со схемой текст выходит за границы (правая сторона). Сам текст достаточно большой и в некоторых местах перекрывает значки. Как решение, можно уменьшить все элементы на картинке и скомпоновать их так, чтобы они не перекрывали друг друга.

**Comment by Ana-Majer** [comment]
Не знаю, на чем ты смотрел, на телефоне или ноутбуке, у меня все отлично, само изображение подстраивается под разрешение экрана, все элементы на своих местах, ничего друг на друга не "скачет"

**Comment by Ana-Majer** [comment]
Посмотрела на телефоне, там просто обрезается картинка, поэтому текст и выходит за ее пределы, изменила шрифт и расположение текста, теперь выглядит так, как должно быть)

**Comment by eqour** [comment]
Теперь всё хорошо видно, можно закрывать задачу)
