### ISSUE TITLE
Add a link to a separate page

### ISSUE THREAD

**Issue by eqour** [eqour/eireen#7]
Необходимо добавить ссылку на отдельную страницу в разделе на целевой странице или в заголовке целевой страницы.

**Comment by Ana-Majer** [comment]
Сделала ссылку сразу в разделе "Как это работает" на главной странице

**Comment by Ana-Majer** [comment]
Также сделала ссылку на раздел "Контроль и управление" в заголовке

**Comment by eqour** [comment]
Отлично, можно закрывать задачу!
