### ISSUE TITLE
Achievements section

### ISSUE THREAD

**Issue by eqour** [eqour/eireen#8]
Необходимо добавить раздел, описывающий достижения либо планируемые результаты при реализации проекта.

**Comment by eqour** [comment]
@Mirrodep и @Ana-Majer, я создал следующий шаблон раздела:
![template](https://user-images.githubusercontent.com/94632924/145682129-01957f97-3c9d-4742-beb1-1ff4f95eca16.png)
Возникли вопросы насчёт оформления и заполнения раздела:
1. Какую информацию добавить в раздел? Моё предложение:

- 3 диплома участника проектов
- 80 000 автономных групп светильников
- 21+ задействованных городов
   
2. Нужно ли добавлять какой-нибудь эффект или анимацию к цифрам? Например, при прокрутке к этому разделу увеличивать цифры от нуля до необходимого значения.

**Comment by Ana-Majer** [comment]
Да, можно добавить эту информацию в раздел, насчет эффекта, тоже хорошая идея)

**Comment by eqour** [comment]
@Ana-Majer, новый раздел готов!
